version: '3.9'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mattermost-network

  # MinIO (S3-compatible storage)
  minio:
    image: minio/minio
    container_name: minio
    command: server /data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_PORT_CONSOLE}:${MINIO_PORT_CONSOLE}" # MinIO Console
      - "${MINIO_PORT_WEB}:${MINIO_PORT_WEB}" # MinIO Web Interface
    volumes:
      - minio_data:/data
    networks:
      - mattermost-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - mattermost
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    volumes:
      - ./nginx.conf:/etc/nginx.conf:ro
    networks:
      - mattermost-network

  # Mattermost App
  mattermost:
    image: mattermost/mattermost-team-edition:latest
    container_name: mattermost
    environment:
      MM_SQLSETTINGS_DRIVERNAME: ${MM_SQL_DRIVERNAME}
      MM_SQLSETTINGS_DATASOURCE: ${MM_SQL_DATASOURCE}
      MM_FILESETTINGS_DRIVERNAME: ${MM_FILE_DRIVERNAME}
      MM_FILESETTINGS_DIRECTORY: ${MM_FILE_DIRECTORY}
      MM_FILESETTINGS_ENABLEPUBLICLINKS: ${MM_FILE_ENABLEPUBLICLINKS}
      MM_FILESETTINGS_PUBLICLINKSURL: ${MM_FILE_PUBLICLINKSURL}
      MM_FILESETTINGS_AMAZONS3ENDPOINT: ${MM_FILE_S3_ENDPOINT}
      MM_FILESETTINGS_AMAZONS3ACCESSKEYID: ${MM_FILE_S3_ACCESSKEYID}
      MM_FILESETTINGS_AMAZONS3SECRETACCESSKEY: ${MM_FILE_S3_SECRETACCESSKEY}
      MM_FILESETTINGS_AMAZONS3BUCKET: ${MM_FILE_S3_BUCKET}
      MM_FILESETTINGS_AMAZONS3BUCKETURL: ${MM_FILE_S3_BUCKETURL}
      MM_FILESETTINGS_AMAZONS3REGION: ${MM_FILE_S3_REGION}
    ports:
      - "${MATTERMOST_PORT}:${MATTERMOST_PORT}"
    depends_on:
      - postgres
      - minio
    volumes:
      - mattermost_data:/mattermost/data
      - mattermost_logs:/mattermost/logs
      - mattermost_plugins:/mattermost/plugins
      - mattermost_client-plugins:/mattermost/client-plugins
    networks:
      - mattermost-network

networks:
  mattermost-network:
    driver: bridge

volumes:
  postgres_data:
  minio_data:
  mattermost_data:
  mattermost_logs:
  mattermost_plugins:
  mattermost_client-plugins:
