version: '3.9'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mattermost
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mattermost-network

  # MinIO (S3-compatible storage)
  minio:
    image: minio/minio
    container_name: minio
    command: server /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000" # MinIO Console
      - "9001:9001" # MinIO Web Interface
    volumes:
      - minio_data:/data
    networks:
      - mattermost-network

  # Mattermost App
  mattermost:
    image: mattermost/mattermost-team-edition:latest
    container_name: mattermost
    environment:
      MM_SQLSETTINGS_DRIVERNAME: postgres
      MM_SQLSETTINGS_DATASOURCE: "postgres://postgres:password@postgres:5432/mattermost?sslmode=disable&connect_timeout=10"
      MM_FILESETTINGS_DRIVERNAME: local
      MM_FILESETTINGS_DIRECTORY: ./data
      MM_FILESETTINGS_ENABLEPUBLICLINKS: "true"
      MM_FILESETTINGS_PUBLICLINKSURL: "http://localhost:8065"
      MM_FILESETTINGS_AMAZONS3ENDPOINT: http://minio:9000
      MM_FILESETTINGS_AMAZONS3ACCESSKEYID: minioadmin
      MM_FILESETTINGS_AMAZONS3SECRETACCESSKEY: minioadmin
      MM_FILESETTINGS_AMAZONS3BUCKET: mattermost
      MM_FILESETTINGS_AMAZONS3BUCKETURL: http://localhost:9000/mattermost
      MM_FILESETTINGS_AMAZONS3REGION: us-east-1
    ports:
      - "8065:8065"
    depends_on:
      - postgres
      - minio
    volumes:
      - mattermost_data:/mattermost/data
      - mattermost_logs:/mattermost/logs
      - mattermost_plugins:/mattermost/plugins
      - mattermost_client-plugins:/mattermost/client-plugins
    networks:
      - mattermost-network

networks:
  mattermost-network:
    driver: bridge

volumes:
  postgres_data:
  minio_data:
  mattermost_data:
  mattermost_logs:
  mattermost_plugins:
  mattermost_client-plugins:
